### ISSUE TITLE
different erfcx approximation error on pytorch

### ISSUE THREAD

**Issue by gaosh** [necludov/group-sparsity-sbp#2]
Hi,  I try to re-implement your paper on pytorch. I changed your erfcx function to adapt pytorch tensor. After compared to the values of special.erfcx(x), the average absolute error is approximate 2.11-08, and average relative error is approximate  3.91e-08, both are much larger than your erfcx approximation. Could this be a problem?

Thanks ,
Shangqian

**Comment by da-molchanov** [comment]
Dear Shangqian,
3.91e-0.8 relative error in erfcx seems as a tight enough approximation. I don't think it would cause any problems. We only use erfcx to calculate the mean and the snr of the variational distribution and only use it during pruning and inference. It would not affect training at all.

Best regards,
Dmitry

**Comment by gaosh** [comment]
Thanks for your reply.
